### PR TITLE
[FEATURE] add $name->getFullgivenname() to get given name in original order.

### PR DESCRIPTION
**Pull request by jpmschuler**
Context: #21 
An input of `Schuler, J. Peter M.` results in
```php 
    [firstname] => Peter
    [initials] => J. M.
    [lastname] => Schuler
```
and thus won't allow to re-compose the original name. As the discussion in #21 showed a change of current behavior might not only be breaking, but its desirability really depends on the situation. 

Thus, this change proposes to add a new component `fullgivenname` to the parser which consists of `firstname`,`middlename`,`initials` in original order. To prevent any breakage this attribute is not exposed to `$name->getAll()`.

Documentation and a single poorly written unit test included.

### CODE REVIEW

**Comment by wyrfel** [comment]
Hey, @jpmschuler, thanks for this - as always, sorry for the delay, i'll get back to you very soon.

**Comment by wyrfel** [comment]
Actually - what i can say right now is - i think the `getFullgivenname()` function doesn't need an extra parser as all the parts are put on the `Name` instance in the right order anyway. As such, this method can be implemented without an extra parsing step, just as an export mode on the `Name` class. Does that make sense?

**Comment by jpmschuler** [comment]
Get your point, will refactor as soon as time comes up.

**Comment by wyrfel** [comment]
Has been replaced by #27 .

**Pull request closed without merging**
